version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Pre-build phase"
      - npm ci
  build:
    commands:
      - echo "Build phase"
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase"
      - aws s3 sync dist/ s3://my-bucket/my-app/

artifacts:
  files:
    - '**/*'
  base-directory: dist
