version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.9
  pre_build:
    commands:
      - echo "Pre-build phase"
      - npm ci
  build:
    commands:
      - echo "Build phase"
      - npm run build

  post_build:
    commands:
      - echo "Collecting build logs..."
      - python lambda_function.py
      - echo "DONE!!"

artifacts:
  files:
    - lambda_function.py
